// Generated by build/build.py. Do not edit.
window.BUILD_STAMP = {
 "commit": "fd0770b",
 "dirty": true,
 "corpus_sha256": "274d620ecc2f9c2e37fee3a2f97851ddee47b24865b65eac93cdca272f1354e1",
 "generated": "2026-09-21T10:54:44+00:00",
 "study": "sensitivity_2026-09-19"
};
