// Generated by build/decision_export.py. Do not edit.
window.DECISION_CARD = {
 "generated": "2026-09-26",
 "panel": {
  "name": "pi05_libero_object",
  "policy_class": "pi05",
  "suite": "libero_object",
  "n_runs": 8,
  "runs": [
   "pt2k88_s0",
   "pt2k88_s1",
   "pt2k88_s2",
   "pt2k88_s3",
   "pt2k88_s4",
   "pt2k88_s5",
   "pt2k88_s6",
   "pt2k88_s7"
  ],
  "n_tasks": 10,
  "episodes_per_cell": 100,
  "total_episodes": 8000,
  "venue": "simulation_benchmark",
  "note": "Eight retrainings of one recipe on identical data. The true difference between any two arms is zero."
 },
 "arm_size": 2,
 "counts": {
  "n_cells": 2100,
  "episode_level_rejects": 869,
  "retrain_level_rejects": 36,
  "both_reject": 36,
  "episode_only_rejects": 833,
  "retrain_rejects_are_subset": true
 },
 "headline": {
  "task": 1,
  "arm_a": [
   "pt2k88_s2",
   "pt2k88_s6"
  ],
  "arm_b": [
   "pt2k88_s3",
   "pt2k88_s4"
  ],
  "x_a": 32,
  "n_a": 200,
  "x_b": 114,
  "n_b": 200,
  "rate_a": 16.0,
  "rate_b": 57.0,
  "gap_pp": 41.0,
  "z": -8.51629235439,
  "welch_t": -2.0474422947,
  "df": 1,
  "t_crit": 12.706,
  "p_two_sided": 1.64742633104e-17
 },
 "reference_classes": [
  {
   "retrains_per_arm": 2,
   "episodes_per_arm": 200,
   "n_comparisons": 2100,
   "curve": [
    {
     "threshold_pp": 0,
     "false_positive_rate": 1.0
    },
    {
     "threshold_pp": 2,
     "false_positive_rate": 0.851904761905
    },
    {
     "threshold_pp": 4,
     "false_positive_rate": 0.680952380952
    },
    {
     "threshold_pp": 6,
     "false_positive_rate": 0.548095238095
    },
    {
     "threshold_pp": 8,
     "false_positive_rate": 0.434285714286
    },
    {
     "threshold_pp": 10,
     "false_positive_rate": 0.345238095238
    },
    {
     "threshold_pp": 12,
     "false_positive_rate": 0.277619047619
    },
    {
     "threshold_pp": 14,
     "false_positive_rate": 0.203333333333
    },
    {
     "threshold_pp": 16,
     "false_positive_rate": 0.158095238095
    },
    {
     "threshold_pp": 18,
     "false_positive_rate": 0.123333333333
    },
    {
     "threshold_pp": 20,
     "false_positive_rate": 0.0957142857143
    },
    {
     "threshold_pp": 22,
     "false_positive_rate": 0.0752380952381
    },
    {
     "threshold_pp": 24,
     "false_positive_rate": 0.062380952381
    },
    {
     "threshold_pp": 26,
     "false_positive_rate": 0.047619047619
    },
    {
     "threshold_pp": 28,
     "false_positive_rate": 0.0347619047619
    },
    {
     "threshold_pp": 30,
     "false_positive_rate": 0.0257142857143
    },
    {
     "threshold_pp": 32,
     "false_positive_rate": 0.0171428571429
    },
    {
     "threshold_pp": 34,
     "false_positive_rate": 0.0119047619048
    },
    {
     "threshold_pp": 36,
     "false_positive_rate": 0.00809523809524
    },
    {
     "threshold_pp": 38,
     "false_positive_rate": 0.00428571428571
    },
    {
     "threshold_pp": 40,
     "false_positive_rate": 0.00190476190476
    }
   ]
  },
  {
   "retrains_per_arm": 3,
   "episodes_per_arm": 300,
   "n_comparisons": 2800,
   "curve": [
    {
     "threshold_pp": 0,
     "false_positive_rate": 1.0
    },
    {
     "threshold_pp": 2,
     "false_positive_rate": 0.813928571429
    },
    {
     "threshold_pp": 4,
     "false_positive_rate": 0.616785714286
    },
    {
     "threshold_pp": 6,
     "false_positive_rate": 0.483214285714
    },
    {
     "threshold_pp": 8,
     "false_positive_rate": 0.372857142857
    },
    {
     "threshold_pp": 10,
     "false_positive_rate": 0.2775
    },
    {
     "threshold_pp": 12,
     "false_positive_rate": 0.201071428571
    },
    {
     "threshold_pp": 14,
     "false_positive_rate": 0.144285714286
    },
    {
     "threshold_pp": 16,
     "false_positive_rate": 0.1025
    },
    {
     "threshold_pp": 18,
     "false_positive_rate": 0.0725
    },
    {
     "threshold_pp": 20,
     "false_positive_rate": 0.0525
    },
    {
     "threshold_pp": 22,
     "false_positive_rate": 0.0382142857143
    },
    {
     "threshold_pp": 24,
     "false_positive_rate": 0.0235714285714
    },
    {
     "threshold_pp": 26,
     "false_positive_rate": 0.0128571428571
    },
    {
     "threshold_pp": 28,
     "false_positive_rate": 0.0075
    },
    {
     "threshold_pp": 30,
     "false_positive_rate": 0.00392857142857
    },
    {
     "threshold_pp": 32,
     "false_positive_rate": 0.000714285714286
    },
    {
     "threshold_pp": 34,
     "false_positive_rate": 0.000357142857143
    },
    {
     "threshold_pp": 36,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 38,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 40,
     "false_positive_rate": 0.0
    }
   ]
  },
  {
   "retrains_per_arm": 4,
   "episodes_per_arm": 400,
   "n_comparisons": 350,
   "curve": [
    {
     "threshold_pp": 0,
     "false_positive_rate": 1.0
    },
    {
     "threshold_pp": 2,
     "false_positive_rate": 0.797142857143
    },
    {
     "threshold_pp": 4,
     "false_positive_rate": 0.594285714286
    },
    {
     "threshold_pp": 6,
     "false_positive_rate": 0.448571428571
    },
    {
     "threshold_pp": 8,
     "false_positive_rate": 0.32
    },
    {
     "threshold_pp": 10,
     "false_positive_rate": 0.214285714286
    },
    {
     "threshold_pp": 12,
     "false_positive_rate": 0.151428571429
    },
    {
     "threshold_pp": 14,
     "false_positive_rate": 0.105714285714
    },
    {
     "threshold_pp": 16,
     "false_positive_rate": 0.0685714285714
    },
    {
     "threshold_pp": 18,
     "false_positive_rate": 0.0428571428571
    },
    {
     "threshold_pp": 20,
     "false_positive_rate": 0.0228571428571
    },
    {
     "threshold_pp": 22,
     "false_positive_rate": 0.0114285714286
    },
    {
     "threshold_pp": 24,
     "false_positive_rate": 0.00285714285714
    },
    {
     "threshold_pp": 26,
     "false_positive_rate": 0.00285714285714
    },
    {
     "threshold_pp": 28,
     "false_positive_rate": 0.00285714285714
    },
    {
     "threshold_pp": 30,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 32,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 34,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 36,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 38,
     "false_positive_rate": 0.0
    },
    {
     "threshold_pp": 40,
     "false_positive_rate": 0.0
    }
   ]
  }
 ]
};
