// Generated by build/decision_export.py. Do not edit.
window.DECISION_CARD = {
 "generated": "2026-09-21",
 "panel": {
  "name": "pi05_libero_object",
  "policy_class": "pi05",
  "suite": "libero_object",
  "n_runs": 8,
  "runs": [
   "pt2k88_s0",
   "pt2k88_s1",
   "pt2k88_s2",
   "pt2k88_s3",
   "pt2k88_s4",
   "pt2k88_s5",
   "pt2k88_s6",
   "pt2k88_s7"
  ],
  "n_tasks": 10,
  "episodes_per_cell": 100,
  "total_episodes": 8000,
  "venue": "simulation_benchmark",
  "note": "Eight retrainings of one recipe on identical data. The true difference between any two arms is zero."
 },
 "arm_size": 2,
 "counts": {
  "n_cells": 2100,
  "episode_level_rejects": 869,
  "retrain_level_rejects": 36,
  "both_reject": 36,
  "episode_only_rejects": 833,
  "retrain_rejects_are_subset": true
 },
 "headline": {
  "task": 1,
  "arm_a": [
   "pt2k88_s2",
   "pt2k88_s6"
  ],
  "arm_b": [
   "pt2k88_s3",
   "pt2k88_s4"
  ],
  "x_a": 32,
  "n_a": 200,
  "x_b": 114,
  "n_b": 200,
  "rate_a": 16.0,
  "rate_b": 56.99999999999999,
  "gap_pp": 40.99999999999999,
  "z": -8.51629235438931,
  "welch_t": -2.0474422946995814,
  "df": 1,
  "t_crit": 12.706,
  "p_two_sided": 1.6474263310395285e-17,
  "per_run_a": [
   17.0,
   15.0
  ],
  "per_run_b": [
   37.0,
   77.0
  ]
 },
 "matrix": [
  {
   "task": 0,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 88,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 58,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 83,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 76,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 79,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 72,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 89,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 87,
     "n": 100
    }
   ],
   "min": 57.99999999999999,
   "max": 89.0,
   "spread": 31.000000000000007
  },
  {
   "task": 1,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 21,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 22,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 17,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 37,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 77,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 19,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 15,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 30,
     "n": 100
    }
   ],
   "min": 15.0,
   "max": 77.0,
   "spread": 62.0
  },
  {
   "task": 2,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 68,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 87,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 92,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 95,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 88,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 79,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 85,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 85,
     "n": 100
    }
   ],
   "min": 68.0,
   "max": 95.0,
   "spread": 27.0
  },
  {
   "task": 3,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 11,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 46,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 33,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 50,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 48,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 30,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 47,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 40,
     "n": 100
    }
   ],
   "min": 11.0,
   "max": 50.0,
   "spread": 39.0
  },
  {
   "task": 4,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 88,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 87,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 86,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 92,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 82,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 87,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 86,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 84,
     "n": 100
    }
   ],
   "min": 82.0,
   "max": 92.0,
   "spread": 10.0
  },
  {
   "task": 5,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 51,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 74,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 39,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 63,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 53,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 47,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 64,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 47,
     "n": 100
    }
   ],
   "min": 39.0,
   "max": 74.0,
   "spread": 35.0
  },
  {
   "task": 6,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 85,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 46,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 78,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 89,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 85,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 66,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 44,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 69,
     "n": 100
    }
   ],
   "min": 44.0,
   "max": 89.0,
   "spread": 45.0
  },
  {
   "task": 7,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 74,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 83,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 79,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 69,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 79,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 57,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 67,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 69,
     "n": 100
    }
   ],
   "min": 56.99999999999999,
   "max": 83.0,
   "spread": 26.000000000000007
  },
  {
   "task": 8,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 73,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 83,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 86,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 85,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 83,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 68,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 73,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 76,
     "n": 100
    }
   ],
   "min": 68.0,
   "max": 86.0,
   "spread": 18.0
  },
  {
   "task": 9,
   "cells": [
    {
     "run": "pt2k88_s0",
     "successes": 40,
     "n": 100
    },
    {
     "run": "pt2k88_s1",
     "successes": 25,
     "n": 100
    },
    {
     "run": "pt2k88_s2",
     "successes": 22,
     "n": 100
    },
    {
     "run": "pt2k88_s3",
     "successes": 23,
     "n": 100
    },
    {
     "run": "pt2k88_s4",
     "successes": 18,
     "n": 100
    },
    {
     "run": "pt2k88_s5",
     "successes": 39,
     "n": 100
    },
    {
     "run": "pt2k88_s6",
     "successes": 36,
     "n": 100
    },
    {
     "run": "pt2k88_s7",
     "successes": 28,
     "n": 100
    }
   ],
   "min": 18.0,
   "max": 40.0,
   "spread": 22.0
  }
 ]
};
